# Generated by Django 2.2.4 on 2019-08-31 04:14

import books.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=books.helpers.imageUpload)),
                ('book_name', models.CharField(max_length=30)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(choices=[('Mechancial', 'Mechancial'), ('Computer Science', 'Computer Science'), ('Information science', 'Information science'), ('Electrical', 'Electrical'), ('Civil', 'Civil'), ('Biotechnology', 'Biotechnology'), ('Chemical', 'Chemical'), ('Electronics and Communication', 'Electronics and Communication'), ('Industrial and Management', 'Industrial and Management'), ('Medical Electronics', 'Medical Electronics')], max_length=40)),
                ('semester', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1, max_length=20)),
                ('cost', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
