# Generated by Django 2.2.4 on 2019-08-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190831_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='semester',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1),
        ),
    ]
