# Generated by Django 2.2.4 on 2019-09-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='owner',
        ),
    ]
