# Generated by Django 2.2.4 on 2019-08-31 02:30

import accounts.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_num',
            field=models.PositiveIntegerField(unique=True, validators=[accounts.helpers.validatePhoneNum]),
        ),
    ]
