# Generated by Django 2.2.4 on 2019-08-30 18:44

import accounts.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190831_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(default='msrit', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='contact_num',
            field=models.IntegerField(default=9071194565, unique=True, validators=[accounts.helpers.validatePhoneNum]),
            preserve_default=False,
        ),
    ]
